### ISSUE TITLE
We have a problem with big HTML

### ISSUE THREAD

**Issue by NorthDev10** [iamstevendao/vue-tel-input#200]
Hello!
To improve the PageSpeed score, we need to shorten the HTML. Can we use v-if and v-once instead of v-show in the list of countries?

Could we apply the following changes to the vue-tel-input.vue file?
`<ul ref="list" class="vti__dropdown-list" v-if="open" v-once :class="dropdownOpenDirection">`

![image](https://user-images.githubusercontent.com/18488835/87875421-c0ec0180-c9d9-11ea-9f1f-d6316d30d2e1.png)

**Comment by WildEgo** [comment]
@iamstevendao Hey mate any news on this? Would be amazing to have this addressed

**Comment by iamstevendao** [comment]
@NorthDev10 @WildEgo Thanks for the suggestion, it is fixed in [v5.3.0](https://github.com/iamstevendao/vue-tel-input/releases/tag/v5.3.0).
