### ISSUE TITLE
Support for vuejs 3

### ISSUE THREAD

**Issue by gilons** [iamstevendao/vue-tel-input#229]
Hello, everyone. 
Recently I wanted to use this library in my vue3 project but I was not able. 
it is crashing with the error 
`vue.js:6848 Uncaught (in promise) TypeError: selfHook.bind is not a function`
 any fix for that will be highly appreciated

**Comment by josteinkirkebak** [comment]
Did you solve this? @gilons 

I think i have figured out this is related to importing a component async from an external package.

**Comment by victorybiz** [comment]
Any updates on support for Vue 3 ?

**Comment by victorybiz** [comment]
I made little Vue 3 support for a fork of this plugin, anyone trying to use this in a Vue 3 project can use my little workaround till @iamstevendao releases official support for Vue 3.

https://github.com/victorybiz/vue3-tel-input

**Comment by daaanny90** [comment]
@victorybiz if you found a solution, why don't you make a PR?

**Comment by MikeyBeLike** [comment]
I personally don't have the time to make a PR atm but came across this and have a quick easy solution if anybody is already stuck with Vue 3 and still needs to use this.

I created a quick [gist](https://gist.github.com/MikeyBeLike/75ef6bd3cd0f7db45c1743cafc528f14) and also a [codesandbox](https://codesandbox.io/s/vue3-intl-tel-input-0ty59) to demonstrate use with the [vanilla package](https://github.com/jackocnr/intl-tel-input)

**Comment by ArtemZHR** [comment]
> I made little Vue 3 support for a fork of this plugin, anyone trying to use this in a Vue 3 project can use my little workaround till @iamstevendao releases official support for Vue 3.
> 
> https://github.com/victorybiz/vue3-tel-input

Can you tell me how to track the value using "v-model" via vuelidate?

**Comment by vasiiil** [comment]
> I made little Vue 3 support for a fork of this plugin, anyone trying to use this in a Vue 3 project can use my little workaround till @iamstevendao releases official support for Vue 3.
> 
> https://github.com/victorybiz/vue3-tel-input

Hi. I tried your fork, still the directive v-model doesn't change the virable of parent component from data. for example, [sandbox](https://codesandbox.io/s/nervous-wozniak-qpww5)
Could you help me with this, please?

**Comment by iamstevendao** [comment]
Sorry for the delay guys. Support for vue3 is available at `vue-tel-input@next`: [guide](https://iamstevendao.github.io/vue-tel-input/documentation/next.html)

Let me know if you find any issues.

**Comment by maraispierre** [comment]
Hello,

I tried to use support for Vue3  but I have those errors when  I click on input : 

`
runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: Cannot read property 'setSelectionRange' of undefined
    at f (vue-tel-input.umd.min.js?e75b:formatted:173)
    at Proxy.onFocus (vue-tel-input.umd.min.js?e75b:formatted:5857)
    at Object.onFocus.e.<computed>.e.<computed> (vue-tel-input.umd.min.js?e75b:formatted:3447)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at HTMLInputElement.invoker (runtime-dom.esm-bundler.js?830f:333)

`
Do you have any solutions ?

**Comment by vasiiil** [comment]
> Hello @iamstevendao ,
> 
> I tried to use support for Vue3 but I have those errors when I click on input :
> 
> ```
> runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: Cannot read property 'setSelectionRange' of undefined
>     at f (vue-tel-input.umd.min.js?e75b:formatted:173)
>     at Proxy.onFocus (vue-tel-input.umd.min.js?e75b:formatted:5857)
>     at Object.onFocus.e.<computed>.e.<computed> (vue-tel-input.umd.min.js?e75b:formatted:3447)
>     at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
>     at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
>     at HTMLInputElement.invoker (runtime-dom.esm-bundler.js?830f:333)
> ```
> 
> Do you have any solutions ?

I've got the same problem. Do you resolve it or wait official release?

**Comment by iamstevendao** [comment]
@maraispierre @vasiiil are you guys using `vue-tel-input` in a component using composition API?

**Comment by vasiiil** [comment]
> @maraispierre @vasiiil are you guys using `vue-tel-input` in a component using composition API?

No, I just use the `vue-tel-input` tag in the component as described in the block [Getting started](https://iamstevendao.github.io/vue-tel-input/documentation/next.html#getting-started)

**Comment by maraispierre** [comment]
@iamstevendao on my side, yes I try to use vue-tel-input in an component using composition API. I will try to use it with Option API.

**Comment by maraispierre** [comment]
@iamstevendao I try to use `vue-tel-input` with Option API, it doesn't work.

**Comment by vasiiil** [comment]
@iamstevendao hi
i'm update vue version to 3.1.1 and this error (Cannot read property 'setSelectionRange' of undefined) no longer reproduced.
but i have another error: countries doesn't displayed.
my import plugin code:

```
import { createApp } from 'vue';
import VueTelInput from 'vue-tel-input';
import 'vue-tel-input/dist/vue-tel-input.css';

Vue.use(VueTelInput, {
    defaultCountry: 'RU',
    dropdownOptions: {
        showDialCodeInSelection: false
    },
    inputOptions: {
        placeholder: 'Мобильный телефон',
    },
    invalidMsg: 'Некорректный номер телефона',
    mode: 'international',
    preferredCountries: ['RU', 'KZ', 'KG', 'BY']
});
Vue.mount('#app');
```

**Comment by maraispierre** [comment]
@iamstevendao Same issue when I will upgrade my version to 3.1.1

**Comment by vasiiil** [comment]
@iamstevendao hello
I think I found a bug.
reproduce:
1.set the validCharactersOnly prop to true
2.enter the correct phone number
3.enter a letter

if you enter a digit after the letter, the letters will be erased, and only a valid phone number will remain in the input field.

If after formatting the entered phone number (when the last digit is entered, the number is automatically formatted), enter a digit, the letters will again become unavailable for input.

thus, invalid characters can only be entered when there is a valid phone number in the input field and phoneObject.valid === true

**Comment by DjilanoS** [comment]
@iamstevendao the plugin doesn't work properly on Vue 3. after mounting the plugin on Vue the Tel input shows up, formatting works. but using ref/reactive states in the Composition api and using `v-model="phone"` does nothing.
Whatever is being typed in `<vue-tel-input v-model="phone"></vue-tel-input>` won't add the typed numbers to the `phone` ref.  

Also tried switching up ref for 
```js
setup: () => {
    const state = reactive({
        phone: ''
    })

   return { ...toRefs(state) }
}
```

```html
<vue-tel-input v-model="phone"></vue-tel-input>
{{ phone }}
```

Nothing seem to work, data is not reactive.

**Comment by iamstevendao** [comment]
Hey guys, sorry for the delay! I have addressed this issue in [v6.0.0-beta.1](https://github.com/iamstevendao/vue-tel-input/releases/tag/v6.0.0-beta.1).

Can anyone confirm that it's working now? Feel free to re-open the issue if not.

**Comment by vasiiil** [comment]
> Hey guys, sorry for the delay! I have addressed this issue in [v6.0.0-beta.1](https://github.com/iamstevendao/vue-tel-input/releases/tag/v6.0.0-beta.1).
> 
> Can anyone confirm that it's working now? Feel free to re-open the issue if not.

 
@iamstevendao hi
Thank yuo for answer.
In vue-tel-input.vue you changed the value prop to the modelValue, but in computed and mounted still use this.value.
Didn’t there also need to replace the value with the modelValue?

mounted:
```
if (this.value) {
  this.phone = this.value.trim();
}
```
computed:
```
this.$nextTick(() => {
  // In case `v-model` is not set, we need to update the `phone` to be new formatted value
  if (value && !this.value) {
    this.phone = value;
  }
});
```

**Comment by iamstevendao** [comment]
@vasiiil Thanks for noticing! 6.0.0-beta.2 is up!

**Comment by Luksona2006** [comment]
There are still some bugs, on changing country it doesn't changes Dial Code in the input and changes only flag, also I can't write anything in input without hitting Enter key on every attempt to write any number

**Comment by MorningPants** [comment]
> Sorry for the delay guys. Support for vue3 is available at `vue-tel-input@next`: [guide](https://iamstevendao.github.io/vue-tel-input/documentation/next.html)
> 
> Let me know if you find any issues.

Hi! I'm getting a 404 on all of your documentation pages, is there any other way to see them?

**Comment by iamstevendao** [comment]
@MorningPants can you try this? https://iamstevendao.com/vue-tel-input/guide/getting-started.html
