### ISSUE TITLE
+3800987654321 is valid, why?

### ISSUE THREAD

**Issue by olexandrbig** [iamstevendao/vue-tel-input#237]
is not valid phone number in Ukraine but plugin allow to enter +3800*********

**Comment by olexandrbig** [comment]
ok, know why, https://github.com/google/libphonenumber
but can somebody suggest how to improve this even with pull request idea

**Comment by iamstevendao** [comment]
@olexandrbig maybe we need to raise the issue in the https://github.com/google/libphonenumber repo?
<img width="369" alt="Screen Shot 2021-06-16 at 17 11 35" src="https://user-images.githubusercontent.com/15044203/122174251-ea512e00-cec5-11eb-9316-333d5d67bf3b.png">
