### ISSUE TITLE
Flag is not present when showDialCode

### ISSUE THREAD

**Issue by valeriu9** [iamstevendao/vue-tel-input#245]
When adding property showDialCode in InputOptions the flag disappears when is in the initial state. If I insert 2 numbers in the input field then the flag appears.  I met this problem for version 5.1.0, I downgraded it to v4.4.2 and it works fine with the same code.
inputOptions: {
          showDialCode: true
          }
![flag error](https://user-images.githubusercontent.com/43374180/110768505-93e5ab00-8257-11eb-8942-2d259508577a.gif)

**Comment by iamstevendao** [comment]
@valeriu9 Can you update to the latest release to see if it still happens? If it does, please re-open the issue.

**Comment by bogdan12893** [comment]
Similar problem, when I change the route in nuxt. The flag appears only after refreshing the page. 😕 @iamstevendao 
Using: Nuxt 2, vue-tel-input ^5.11.0
