### ISSUE TITLE
Cannot read property 'toUpperCase' of null

### ISSUE THREAD

**Issue by GMounir** [iamstevendao/vue-tel-input#255]
If prop **onlyCountries** has one country and the user try to change the country code the error throw  **Cannot read property 'toUpperCase' of null**
Thank you

**Comment by mxlpitelik** [comment]
Same trouble if you added country to ignoredCountries and starts typing number phone number of ignored country.....

![error screenshot](https://user-images.githubusercontent.com/10188794/118141290-dec79e80-b411-11eb-82ce-4d0ba4b1105e.png)

**Comment by iamstevendao** [comment]
Hey guys, sorry for the delay. it should be fixed in [v5.6.1](https://github.com/iamstevendao/vue-tel-input/releases/tag/v5.6.1).
