### ISSUE TITLE
defaultCountry by dialcode not working

### ISSUE THREAD

**Issue by rekhasf** [iamstevendao/vue-tel-input#259]
defaultCountry by dialcode not working

**Comment by iamstevendao** [comment]
@rekhasf can i have an example?

**Comment by rekhasf** [comment]
here is the code
![image](https://user-images.githubusercontent.com/66454118/116021495-8141fc80-a672-11eb-83e2-0e8a107c09b1.png)


and the result
![image](https://user-images.githubusercontent.com/66454118/116021539-9880ea00-a672-11eb-9f9e-f59b81509fe2.png)

**Comment by iamstevendao** [comment]
@rekhasf are you using v5.2.0?

**Comment by rekhasf** [comment]
v.5.1.0

**Comment by iamstevendao** [comment]
@rekhasf the defaultCountry by dial code is only available from v5.2.0
