### ISSUE TITLE
Validation of number and country + phone

### ISSUE THREAD

**Issue by jewells07** [iamstevendao/vue-tel-input#260]
It takes input in string **(want type = number)**, can't make required field and do we have alternative to get country + phone?
 

` **Template:-** 
    
    <vue-tel-input v-model="phone" v-on:country-changed="countryChanged" />
`

` **script :-** 
    
     data() {
        return {
          phone: null,
          country: null,
          contactForm: {
            countryPhoneNo: null,
          },
        };
      }, methods: {
        countryChanged(country) {
          this.country = '+' + country.dialCode;
        }, async submitData() {
      this.contactForm.countryPhoneNo = this.country + '-' + this.phone;........
      },
`

**Comment by iamstevendao** [comment]
@jewells07 you can use `@input` event: https://iamstevendao.github.io/vue-tel-input/documentation/events.html#input-number-string-phoneobject-object
