### ISSUE TITLE
New breaking version without the polyfills?

### ISSUE THREAD

**Issue by Tofandel** [iamstevendao/vue-tel-input#263]
The built files given to npm are quite huge and filled with polyfills that shouldn't be needed for 99% of users

35% of the package is in fact just polyfills

I'd recommend reconfiguring the babel.config.js and only support recent browsers in a new breaking release or let us transpile the library ourself by also including the source files in the npm package

Another option is to have different builds in different folders for each es version eg:

dist (es5 = current)
dist-es6 (only a very limited set of polyfills based on usage)
dist-es7 (no polyfills at all)

**Comment by Tofandel** [comment]
Here is the result on my fork

https://github.com/Tofandel/vue-tel-input/blob/master/dist-es7/vue-tel-input.umd.min.js
https://github.com/Tofandel/vue-tel-input/blob/master/dist/vue-tel-input.umd.min.js

**Comment by iamstevendao** [comment]
@Tofandel it sounds good!! Are you able to create a PR? otherwise I will have a look later at your suggestion.

**Comment by Tofandel** [comment]
@iamstevendao Here you go, that's quite the PR with a big refresher ;)

**Comment by iamstevendao** [comment]
@Tofandel Thanks for your help! it's available in [v5.4.0](https://github.com/iamstevendao/vue-tel-input/releases/tag/v5.4.0)
