### ISSUE TITLE
Vue 3 - Countries dropdown not working

### ISSUE THREAD

**Issue by thalesagapito** [iamstevendao/vue-tel-input#266]
Hi! Thanks for the work on the lib. I've used it before with Vue 2 but I'm having problems making it work with Vue 3.  
For some reason clicking the arrow does not open the countries dropdown. I've attached some screenshots to better illustrate the problem:
![Captura de Tela 2021-06-21 às 10 48 50](https://user-images.githubusercontent.com/51180770/122773199-842a2980-d27e-11eb-8229-8970b05aaa10.png)
![Captura de Tela 2021-06-21 às 10 47 38](https://user-images.githubusercontent.com/51180770/122773196-82f8fc80-d27e-11eb-8dff-ffda62b07288.png)
As you can see, while the arrow icon works properly, the dropdown element isn't created at all.

**Comment by keziakoko** [comment]
I'm having the exact same issue, dropdown also not working but the arrow changes up and down when clicking.
I have also set "validCharactersOnly: true" in the options and it does not seem to be validating, as I can still enter alphabetical characters I attached a screenshot below:
![image](https://user-images.githubusercontent.com/20063511/122821408-18c37480-d2dd-11eb-9314-24f6630d899c.png)

Using version 6.0.0-beta.0

**Comment by noeGnh** [comment]
I'm also having the same issue with version 6.0.0-beta.0

**Comment by ahmadbjs** [comment]
I have the same issue with this package.. 
i can write in in the input but couldn't able to change the flag of country

**Comment by keziakoko** [comment]
> I'm having the exact same issue, dropdown also not working but the arrow changes up and down when clicking.
> I have also set "validCharactersOnly: true" in the options and it does not seem to be validating, as I can still enter alphabetical characters I attached a screenshot below:
> ![image](https://user-images.githubusercontent.com/20063511/122821408-18c37480-d2dd-11eb-9314-24f6630d899c.png)
> 
> Using version 6.0.0-beta.0

Hi, I have also just noticed that the value in the input is no longer mapping to my v-model variable.

**Comment by thalesagapito** [comment]
@iamstevendao I noticed that the last commit that changed `all-countries.js` (https://github.com/iamstevendao/vue-tel-input/commit/d3d999c04793ad6165f91b682dd9147bde2d9e26) removed order and area codes from country objects, but apparently not all of them. Could this be the problem? Below are the lines left untouched by the commit: 
https://github.com/iamstevendao/vue-tel-input/blob/b6408e2652af04a65f15c714f332b12b308b8683/src/assets/all-countries.js#L456-L461

**Comment by DjilanoS** [comment]
Same issue here, dropdown is not working.

**Comment by DjilanoS** [comment]
> @iamstevendao I noticed that the last commit that changed `all-countries.js` ([d3d999c](https://github.com/iamstevendao/vue-tel-input/commit/d3d999c04793ad6165f91b682dd9147bde2d9e26)) removed order and area codes from country objects, but apparently not all of them. Could this be the problem? Below are the lines left untouched by the commit:
> https://github.com/iamstevendao/vue-tel-input/blob/b6408e2652af04a65f15c714f332b12b308b8683/src/assets/all-countries.js#L456-L461

Same issue here, dropdown is not working in Vue3. Also edited the Guernsey country array. Didn't work.

**Comment by thanhquang1988** [comment]
Hello, do we have any hotfix for this?

**Comment by tsiory** [comment]
Hi guys, any workaround ? It's so frustrating that it's not working on Vue 3

**Comment by DjilanoS** [comment]
@tsiory if you looked at all the issues, you would've noticed my issue including a workaround: https://github.com/iamstevendao/vue-tel-input/issues/270 ..

**Comment by LeonHarper** [comment]
This [fork](https://github.com/victorybiz/vue3-tel-input) apparently solves the drop down issue. I have not tried it myself but some people on #270 say that it is working for them.

**Comment by tsiory** [comment]
@LeonHarper But this fork does not have TypeScript typings...sadly

**Comment by jy02652824** [comment]
![image](https://user-images.githubusercontent.com/28671145/127953135-a803b096-0ad0-4ce7-a8df-44a185652f7d.png)
Delete v-once and it will work

**Comment by iamstevendao** [comment]
Hey guys, sorry for the delay! I have addressed this issue in [v6.0.0-beta.1](https://github.com/iamstevendao/vue-tel-input/releases/tag/v6.0.0-beta.1).

Can anyone confirm that it's working now? Feel free to re-open the issue if not.

**Comment by tsiory** [comment]
Hey Steven, it's working for me. Thanks a lot!
