### ISSUE TITLE
Error on yarn add

### ISSUE THREAD

**Issue by youssef11420** [iamstevendao/vue-tel-input#268]
Hello,

I face this error:
`error [...]\node_modules\vue-tel-input: Command failed.
Exit code: 1
Command: cd docs && npm ci --prefer-offline
Arguments:`

when:
`yarn add vue-tel-input`

It works when version is 5.3.0 or lower.

PS: when I do:
`yarn add https://github.com/iamstevendao/vue-tel-input.git`
It works.

Thanks in advance.

Youssef

**Comment by fccoelho7** [comment]
having the same here

**Comment by SnakeO** [comment]
+1

**Comment by fedeisas** [comment]
+1

**Comment by iamstevendao** [comment]
Sorry guys! It should be fixed in [v5.5.0](https://github.com/iamstevendao/vue-tel-input/releases/tag/v5.5.0)
