### ISSUE TITLE
No way to disable request to ip2c.org

### ISSUE THREAD

**Issue by dr808** [iamstevendao/vue-tel-input#274]
Docs state that `autoDefaultCountry` is used to fetch country by IP. However, when setting to `false` ip2c.org request still gets made.

I've set `onlyCountries` and `defaultCountry` as well and still I get requests to ip2c.org.  Is there any other way to turn it off? There used to be `disableFetchingCountry` but that prop has been removed.

**Comment by dr808** [comment]
Looks like `autoDefaultCountry` works fine. Maybe I had cache issue

**Comment by sanjarbarakayev** [comment]
Sure! I set to false the value of prop `autoDefaultCountry` to false and the issue was fixed)
