### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by VsevolodMr** [iamstevendao/vue-tel-input#275]
<img width="1215" alt="Снимок экрана 2021-07-28 в 17 52 35" src="https://user-images.githubusercontent.com/88099472/127344383-9ce75834-5941-45d2-b99f-1d5e5ce88e2d.png">

**Comment by harshaLekharaju** [comment]
How to resolve this undefined error?

**Comment by mvelosos** [comment]
@harshaLekharaju that happened to me, i was able to resolve by adding a slot for the arrow-icon

**Comment by harshaLekharaju** [comment]
@mvelosos Could you please tell me how to add a slot for arrow-icon?

**Comment by mvelosos** [comment]
@harshaLekharaju  add the template slot inside the component, like this:

`<vue-tel-input
      v-model="phoneNumber"
          <template slot="arrow-icon">
              <span class="vti__dropdown-arrow">&nbsp;▼</span>
          </template>
  </vue-tel-input>`

**Comment by harshaLekharaju** [comment]
@mvelosos Thank you so much. I will try this.

**Comment by orcuntuna** [comment]
> @harshaLekharaju add the template slot inside the component, like this:
> 
> `<vue-tel-input v-model="phoneNumber" <template slot="arrow-icon"> <span class="vti__dropdown-arrow">&nbsp;▼</span> </template> </vue-tel-input>`

That's working, thank you.
