### ISSUE TITLE
Is highlighted class working?

### ISSUE THREAD

**Issue by existe-deja** [iamstevendao/vue-tel-input#278]
When I use arrow navigation, I would like to apply some style to see what I'm selecting. I don't think the highlighted class is applied anymore.

Just tested on the demo website and didn't see anything. Is there some option to activate?

**Comment by iamstevendao** [comment]
@existe-deja it's fixed in [v5.6.2](https://github.com/iamstevendao/vue-tel-input/releases/tag/v5.6.2)
