### ISSUE TITLE
TypeError when you pass the :onlyCountries prop - "Cannot read property 'toUpperCase' of null"

### ISSUE THREAD

**Issue by krckyboy** [iamstevendao/vue-tel-input#280]
Version 6.0.0-beta.1

When I pass the :onlyCountries prop containing an array: ```['ru', 'kz']```, for example, and start entering a number which doesn't have the country code for the provided "only countries" prop the application breaks due to a TypeError that I get with the message: ```"Uncaught TypeError: Cannot read property 'toUpperCase' of null"```. 

So in this case, I type "+3333" and that's when I get this error and the whole application breaks.

```javascript
<vue-tel-input v-model="data.mobile" :onlyCountries="['ru', 'kz']"/>
```
![DeepinScreenshot_select-area_20210811100152](https://user-images.githubusercontent.com/11292329/128992712-aaee324d-0908-4f86-a0b2-302faf0a0445.png)

![DeepinScreenshot_select-area_20210811095815](https://user-images.githubusercontent.com/11292329/128992306-6b44d5c6-2a45-44f6-80b5-a2e8f8086368.png)

**Comment by iamstevendao** [comment]
@krckyboy it's fixed in `v6.0.0-beta.3`
