### ISSUE TITLE
[bug] showDialCode doesn't show flag at start

### ISSUE THREAD

**Issue by lacherogwu** [iamstevendao/vue-tel-input#301]
If the inputOptions.showDialCode = true it doesn't show the flag when first shown
![image](https://user-images.githubusercontent.com/49835614/141500696-90b51880-b13b-4806-a98a-d9642ae15e01.png)

**Comment by riderx** [comment]
Same here

**Comment by riderx** [comment]
@lacherogwu if you use v6 i think it's related to this : https://github.com/iamstevendao/vue-tel-input/pull/300
and not merger yet in v6

**Comment by iamstevendao** [comment]
@riderx it's available in `v6.0.0-beta.5` now!

**Comment by riderx** [comment]
@iamstevendao thanks !
