### ISSUE TITLE
It doesn't work vue 3

### ISSUE THREAD

**Issue by tintin10q** [iamstevendao/vue-tel-input#343]
For me using the code in the docs 

main.ts
```
const app = createApp(App);

import VueTelInput from 'vue-tel-input';
import 'vue-tel-input/dist/vue-tel-input.css';
app.use(VueTelInput)
```

It gives me `[Vue warn]: Component is missing template or render function. `

**Comment by tintin10q** [comment]
I have 6.0.0-beta.7 in my package.json

**Comment by adam1010** [comment]
We're using `6.0.0-beta.7` as well and it's working for us with Vue3. Some of the options aren't working, but it loads and mostly works.

We're importing it locally within a single `.vue` component, not in the global config (we load components async)

```js
import {VueTelInput} from 'vue-tel-input'
import 'vue-tel-input/dist/vue-tel-input.css';

export default defineComponent({
  components: {VueTelInput},
  ...
}
```

**Comment by jdalrymple** [comment]
Im running into the same error with 6.0.1 :/

**Comment by KhaledOmara** [comment]
+1

**Comment by mrnasil** [comment]
https://www.npmjs.com/package/vue3-tel-input-js

**Comment by Anas-shamia** [comment]
Any update for this issue i have the same problem

**Comment by mrnasil** [comment]
> same problem

`import { VueTelInput } from 'vue3-tel-input-js'`
```vue
  <vue-tel-input
          v-model="phone"
          :class="disable ? '!border-bg !bg-bg' : ''"
          :disabled="disable"
          enabled-country-code="true"
          mode="international"
          :name="name"
          style-classes="telinput"
          :type="type"
          :v-bind="options"
          :value="inputValue"
          @blur="handleBlur"
          @input="handleChange"
          @validate="validate"
        ></vue-tel-input>
```

**Comment by sahiln1** [comment]
try using `import "vue-tel-input/dist/style.css";`
It worked for me in vue3 with vue-tel-input version 8.1.0

**Comment by femi-vue** [comment]
the updated version `import 'vue-tel-input/vue-tel-input.css';`
