### ISSUE TITLE
updated to 6.0.1 , got error

### ISSUE THREAD

**Issue by spormeon** [iamstevendao/vue-tel-input#356]
I just updated to 6.0.1 and get this error below, the file doesnt exist, any ideas?

ERROR in ./node_modules/vue-tel-input/dist/vue-tel-input.umd.min.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/davidstanton/adysisstats100/statsadysis/node_modules/vue-tel-input/dist/vue-tel-input.umd.min.js'
 @ ./src/main.js 10:0-40 37:54-65

**Comment by iamstevendao** [comment]
@spormeon that's strange. did you import it following the README? https://github.com/iamstevendao/vue-tel-input/blob/next/README.md
if yes, can you try deleting `node_modules` and install again?

**Comment by spormeon** [comment]
i updated it using npm update , it was on version 6.0.0-beta.7  , i've reverted it back at the moment
![Main_vue_—_statsadysis](https://user-images.githubusercontent.com/8503167/177194943-986f6ca1-f851-4605-b0cc-0bc8a1db62c7.png)

**Comment by spormeon** [comment]
tried deleteing node_modules and installed again etc, still errors: Compiled with problems:X

ERROR in ./node_modules/vue-tel-input/dist/vue-tel-input.umd.min.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/davidstanton/adysisstats100/statsadysis/node_modules/vue-tel-input/dist/vue-tel-input.umd.min.js'

**Comment by iamstevendao** [comment]
should be fixed in `@latest` (`8.2.0`)
