### ISSUE TITLE
sample code for demo

### ISSUE THREAD

**Issue by atlas-wong** [iamstevendao/vue-tel-input#370]
Hi, I found the demo here https://vue-tel-input.iamstevendao.com/ already usable for my usage.
However, I could not reproduce the same layout.
Could I have some sample code of the demo for my reference?
Thanks in advance

**Comment by iamstevendao** [comment]
Here you go: https://github.com/iamstevendao/vue-tel-input/blob/master/docs/.vuepress/theme/components/Home.vue
