### ISSUE TITLE
Nuxt 3

### ISSUE THREAD

**Issue by agracia-foticos** [iamstevendao/vue-tel-input#372]
We are using this component with version 3 RC 9 of Nuxt.

After the installation we realize that the node_modules folder is practically empty, which throws us an error when injecting the component to the Nuxt project.

![image](https://user-images.githubusercontent.com/77386602/188384650-833e26fe-9650-44c7-8183-8da0b2678a27.png)

Package.json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "clean": "npx nuxi-edge@latest cleanup"
  },
  "workspaces": [
    "./../genesis-design-system"
  ],
  "devDependencies": {
    "@iconify-json/fa6-solid": "^1.1.6",
    "@nuxt/postcss8": "^1.1.3",
    "@nuxtjs/tailwindcss": "^5.2.0",
    "autoprefixer": "^10.4.7",
    "postcss": "^8.4.14"
  },
  "dependencies": {
    "@headlessui/vue": "^1.6.7",
    "@intlify/nuxt3": "^0.2.3",
    "@nuxtjs/algolia": "1.1.0",
    "@nuxtjs/device": "github:Redemption198/device-module",
    "@pinia/nuxt": "^0.3.0",
    "@splidejs/vue-splide": "^0.6.7",
    "chart.js": "^3.8.2",
    "nuxt": "^3.0.0-rc.8",
    "pinia": "^2.0.18",
    "redis": "^4.2.0",
    "unplugin-icons": "^0.14.8",
    "vue": "^3.2.37",
    "vue-chart-3": "^3.1.8",
    "vue-tel-input": "^6.0.4",
    "vue3-carousel": "^0.1.40"
  },
  "oldev": {
    "@vue/compiler-sfc": "^3.2.37",
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
    "vue-i18n": "^9.2.2",
    "@intlify/vite-plugin-vue-i18n": "^6.0.0"
  }
}

./src/plugins/vue-tel-input.ts
import {VueTelInput} from 'vue-tel-input';
import 'vue-tel-input/dist/vue-tel-input.css';

export default defineNuxtPlugin(async (nuxtApp) => {
    nuxtApp.vueApp.use(VueTelInput)
})

![image](https://user-images.githubusercontent.com/77386602/188384859-d31efb41-6585-49db-8160-b42fd59dbf00.png)

Thanks in advance

**Comment by desdamo** [comment]
hello same issue

**Comment by iamstevendao** [comment]
hey folks, sorry for this, it should be fixed in `v6.0.5`. feel free to re-open the issue if it's still happening.

**Comment by agracia-foticos** [comment]
> hey folks, sorry for this, it should be fixed in `v6.0.5`. feel free to re-open the issue if it's still happening.

When is version 6.0.5 going to be released? The current one is 6.0.1

**Comment by iamstevendao** [comment]
@agracia-foticos it's already released
<img width="761" alt="image" src="https://user-images.githubusercontent.com/15044203/188567826-4294f121-05cb-4ffb-ac3a-2ea729bb4005.png">

**Comment by agracia-foticos** [comment]
Resolved!! Thanks

**Comment by yesworld** [comment]
I have some problem with resolve component.. I add the plugin in the same way as it was written above.

in my component i try to add plugin
```vue
<template>
    <ClientOnly>
      <vue-tel-input v-model="tel" defaultCountry="RU"/>
    </ClientOnly>
</template>

<script lang="ts" setup>
const tel = ref('+7')
</script>
```

And i got Warn in console:
```
ℹ Vite server warmed up in 107ms  16:48:27
✔ Nitro built in 311 ms       
[Vue warn]: A plugin must either be a function or an object with an "install" function.
[Vue warn]: Failed to resolve component: vue-tel-input
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

<img width="311" alt="image" src="https://user-images.githubusercontent.com/6162264/190860690-9efe0bef-5ada-4c9b-b110-e1316cfeface.png">

What can I do with two problems:
1. If you set country by default and number, then the flag is missing.
2. These are warnings in the console.

Thanks!

**Comment by yesworld** [comment]
@iamstevendao, I tried to solve in this way...

```ts
// nuxt.config.ts
export default defineNuxtConfig({
   vue: {
        compilerOptions:{
            isCustomElement: (tag: string) => ['vue-tel-input'].includes(tag),
        },
    },
```

But got an error:
```
 ERROR  Error while formatting vite error: v-model can only be used on <input>, <textarea> and <select> elements.
```

**Comment by gabrielbarretosantos** [comment]
@yesworld, do you fix this problem? Because in my project, doesn't work and i can't install it in my plugins too :/ 

@iamstevendao any solutions to the problem?

I'm using nuxt with version ^3.2.2

**Comment by oussamalkd** [comment]
using `vueApp.component ` instead of  `vueApp.use` works fine with me

```
import { VueTelInput } from "vue-tel-input";
import 'vue-tel-input/vue-tel-input.css';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component("VueTelInput", VueTelInput)
});
```
