### ISSUE TITLE
Unable to type in numbers in Vue 3

### ISSUE THREAD

**Issue by okeowosv** [iamstevendao/vue-tel-input#376]
Hello, I have installed the plugin as instructed and it renders but I'm unable to type in the file, please check the video below for more understanding https://drive.google.com/file/d/11VaxmBrO6khRt1BIpfg0_vBmp06dUDsY/view?usp=sharing

**Comment by IvanVeskovic** [comment]
Hello, I had same trouble and same behavior, and it was problem with refs or something, I solved that using v-model.

**Comment by mrnasil** [comment]
https://www.npmjs.com/package/vue3-tel-input-js
