### ISSUE TITLE
Country is sometimes not updated when selecting another country

### ISSUE THREAD

**Issue by RonanL** [iamstevendao/vue-tel-input#390]
vue-tel-input 6.0.5
vue 3.2.45
dropdownOptions :
- showDialCodeInList: true
- showDialCodeInSelection: true
- showFlags: true
- showSearchBox: true
preferredCountries: ['FR', 'IT', 'DE', 'ES', 'GB', 'US', 'CA']

When I change the country using the selector, sometimes the prefix changes but the selected country remains the same:
![image](https://user-images.githubusercontent.com/685896/222181263-13524048-3c0a-4d01-a9fc-17a80b15b0d7.png)
![image](https://user-images.githubusercontent.com/685896/222181418-35dcbd68-fb70-4e5b-81e1-f3f3f5ff0ed1.png)
![image](https://user-images.githubusercontent.com/685896/222181530-c568d26d-4c0a-4028-bf0c-26327d2b5ebf.png)

It seems to happen only when selecting from the "preferred countries" block, but I'm not 100% certain on that point.

I did not manage to reproduce this on the demo site.

**Comment by QuentinStG** [comment]
I have the same problem. Seems like this happens when trying to change country after entering a phone number.

**Comment by Nehasoni988** [comment]
I am also facing the same issue. And it happens, anonymously. sometimes when changing country after entering the phone number and sometimes on mount too.

**Comment by Nehasoni988** [comment]
Has anyone found any hack to solve this?

**Comment by obrassard** [comment]
Hey ! We have the same issue on our side. 
Is there any update on this (or on PR #422 ?)

Thanks !

**Comment by iamstevendao** [comment]
Thanks @neha-proxima , the fix is on [v9.1.3](https://github.com/iamstevendao/vue-tel-input/releases/tag/v9.1.3)!

**Comment by RonanL** [comment]
Thanks :D
