### ISSUE TITLE
How to display invalid message

### ISSUE THREAD

**Issue by Jamshidbekdev** [iamstevendao/vue-tel-input#400]

**Comment by Skyline96** [comment]
Here is simple [example](https://codesandbox.io/s/validate-vue-tel-input-syvpni?file=/src/App.vue) incase you still need it :)

**Comment by Jamshidbekdev** [comment]
Thanks, @Skyline96 . However, I did displaying error messages with a custom solution like using events

**Comment by iamstevendao** [comment]
+49175.5888888
