### ISSUE TITLE
search by country code starting with '+' does not work

### ISSUE THREAD

**Issue by Diarten** [iamstevendao/vue-tel-input#402]
i get an error when try to search with + symbol
SyntaxError: Invalid regular expression: /+/: Nothing to repeat (at vue-tel-input.js:3315:1)
 
![image](https://github.com/iamstevendao/vue-tel-input/assets/73462543/8c520ff6-3a46-4493-a21d-f75febfd9102)

**Comment by mehdisolhan** [comment]
I had the same problem. I created a pull request to solve this. #410

If they approve the pr, this issue will be solved.

**Comment by iamstevendao** [comment]
thanks for your help @mehdisolhan . the patch has been released! [v8.1.3](https://github.com/iamstevendao/vue-tel-input/releases/tag/v8.1.3)
