### ISSUE TITLE
Update all-countries.js according to intl-tel-input data.js [main & legacy branches]

### ISSUE THREAD

**Issue by Gkatzos** [iamstevendao/vue-tel-input#415]
Hi,
I would like to know if the two main branches (main & legacy) are going to get an update regarding the country list.
 intl-tel-input data.js is constantly updated while vue-tel-input list is outdated.
 
One example of a crucial change is the following
https://github.com/jackocnr/intl-tel-input/pull/1399

Thanks in advance

**Comment by iamstevendao** [comment]
@Gkatzos thaanks! updated in [v8.3.1](https://github.com/iamstevendao/vue-tel-input/releases/tag/v8.3.1)

**Comment by iamstevendao** [comment]
@Gkatzos done! it's available in `@legacy` (`5.15.0`)

**Comment by AlexeyZelenko** [comment]
Will we have an updated list in vue-tel-input@legacy? 
 +61 461 294 482 or 0461294482
 mobile number is not being accepted. It says "Phone number is wrong for selected country."

 Displayed here correctly:
 https://vue-tel-input.iamstevendao.com/

Thank you.
