### ISSUE TITLE
Error in Vue3

### ISSUE THREAD

**Issue by Vita-zzzxw** [iamstevendao/vue-tel-input#425]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/vue3-tel-input"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/vue3-tel-input/dist/vue3-tel-input.css"
    />
  </head>
  <body>
    <div id="app">
      <vue-tel-input v-model:value="value"></vue-tel-input>
    </div>

    <script>
      const { ref } = Vue;

      const App = {
        setup() {
          const value = ref(null);
          return {
            value,
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(window['vue-tel-input']);
      app.mount('#app');
    </script>
  </body>
</html>

**Comment by iamstevendao** [comment]
@Vita-zzzxw that's a different package, a fork of ours https://github.com/victorybiz/vue3-tel-input
