### ISSUE TITLE
Issue with Dynamic country code selector

### ISSUE THREAD

**Issue by abhishek-classcard** [iamstevendao/vue-tel-input#434]
I am running into a issue with vue tel input where the dynamic country picker is breaking for us, we've been using it for quite sometime, upon mounting the country picker seems to be blank earlier it used to prefill the country we were in, can we get some help here please 
![image (2)](https://github.com/iamstevendao/vue-tel-input/assets/88773474/b7500fed-c390-4b5c-8afc-b25dba1ca79a)

**Comment by jameslgarrett** [comment]
We are also experiencing this issue as well.  Looking into disabling the IP address location detection and defaulting the country as a temporary fix until ip2c.org comes back up

**Comment by ankurbhugra** [comment]
Seems like it is back up again!

**Comment by abhishek-classcard** [comment]
Marking this as closed as the issue has been solved
