### ISSUE TITLE
Search Box  placeholder

### ISSUE THREAD

**Issue by Cadeniuc** [iamstevendao/vue-tel-input#445]
Hi guys,
How I can to change the placeholder for dropdown search box ?
![2024-03-03 12 45 22](https://github.com/iamstevendao/vue-tel-input/assets/21370082/d3e56e76-e0ac-4ec5-ac84-9906f6981f61)

Thanks

**Comment by cyhnkckali** [comment]
@iamstevendao  help plase!!!

**Comment by iamstevendao** [comment]
hi guys, you can customise its style using `vti__search_box` class, or hide it using `dropdownOptions.showSearchBox: false`
```html
<input
            v-if="dropdownOptions.showSearchBox"
            class="vti__input vti__search_box"
            aria-label="Search by country name or country code"
            :placeholder="sortedCountries.length ? sortedCountries[0].name : ''"
            type="text"
            v-model="data.searchQuery"
            @click.stop
        />
```

**Comment by Cadeniuc** [comment]
hi @iamstevendao, I meant change placeholder not hide it(

**Comment by shubhamChaudhariRanium** [comment]
> hi @iamstevendao, I meant to change the placeholder not hide it(

is this update addressing it? I'm encountering a similar issue with this
