### ISSUE TITLE
 Documentation website returns 404

### ISSUE THREAD

**Issue by LakerShot** [iamstevendao/vue-tel-input#465]
Wanna check all props for <vue-tel-input />, but website doesn't response

link - https://educationlink.github.io/vue-tel-input/

<img width="1440" alt="Screenshot 2024-05-22 at 12 57 29" src="https://github.com/iamstevendao/vue-tel-input/assets/48025722/651c5d63-6aaf-4e95-88b9-35db936befad">

**Comment by iamstevendao** [comment]
@LakerShot where did you see this URL? let me know I'll fix it, we have a new home page: https://iamstevendao.com/vue-tel-input/
