### ISSUE TITLE
Can you update vue version from vue.3.4.21 to vue 3.5?

### ISSUE THREAD

**Issue by seyran2002** [iamstevendao/vue-tel-input#483]
my project vue version is 3.5 and i installed this package it didn't work because package vue version is 3.4.21.

**Comment by teddy-dubal** [comment]
Hi , i have the same issue.
Can you please update to 3.5 ?

**Comment by seyran2002** [comment]
@teddy-dubal  Hi, yes this is a very important issue, but it seems to be done in this PR https://github.com/iamstevendao/vue-tel-input/pull/484, I hope they will merge this PR as soon as possible.

**Comment by iamstevendao** [comment]
sorry guys for the delay, vue 3.5 is added in [`v9.2.0`](https://github.com/iamstevendao/vue-tel-input/releases/tag/v9.2.0)

**Comment by seyran2002** [comment]
@iamstevendao thank you so much
