### ISSUE TITLE
Importing CSS from package

### ISSUE THREAD

**Issue by rubensilva3** [iamstevendao/vue-tel-input#489]
I'm integrating with the `vue-tel-input` and while the docs mention that you should import css like this:
 `import 'vue-tel-input/dist/vue-tel-input.css';`

This causes an error in vite: 

![Screenshot 2024-11-26 at 10 37 31](https://github.com/user-attachments/assets/560a4886-be20-475c-9d6d-c747238ff309)

And I see that in package exports it's like this:  
![Screenshot 2024-11-26 at 10 38 18](https://github.com/user-attachments/assets/a3bee5bf-4582-434f-82c7-e9df7d5d578a)

So the import works as  `import 'vue-tel-input/vue-tel-input.css';`, I think the docs should say this to not be misleading :) 

Thanks

**Comment by iamstevendao** [comment]
@rubensilva3 thanks for raising this, it's fixed now!
